services:
  employee-db-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: sqlite:////data/employees.db
    volumes:
      - employee-data:/data

volumes:
  employee-data:
